language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
before_install: 
  - sudo apt-get update
  - sudo apt-get install libdb5.3-dev
  - cpanm --quiet --notest Module::Install::Repository Module::Install::AuthorTests

